#!/bin/bash

pack_ucodes=$(grep "vendor_id" /proc/cpuinfo | head -n 1 | awk '{print $3}')

if [[ "$pack_ucodes" == "GenuineIntel" ]]; then
    echo "intel-ucode" > "$pack_pacman"
elif [[ "$pack_ucodes" == "AuthenticAMD" ]]; then
    echo "amd-ucode"   > "$pack_pacman"
fi