#!/bin/bash

buildauxe="$buildroot/auxel"
builddata="$buildauxe/datum"
buildconf="$buildauxe/config"
buildpack="$buildauxe/packer"
buildlibs="$buildauxe/corest"
buildprof="$buildauxe/profile"



## DISTVARS
test -e "$builddata/raptors.conf" && source "$builddata/raptors.conf"

## USERVARS
if [[ -e "$buildprof/$deprofile" ]];then
    source "$buildprof/$deprofile"
else
    source "$buildprof/default"
fi


## FUNCTION
test -e "$buildauxe/makes" && source "$buildauxe/makes"
test -e "$buildauxe/makos" && source "$buildauxe/makos"


## PACKAGES
raptor_packer="$buildpack/pacmir"
raptor_packfa="$buildpack/packfa"
raptor_packco="$buildpack/packco"


## PROFILING
test -e "$buildprof/$3" && source "$buildprof/$3" 
echo "username : $username"
echo "password : $password"


read -p "Do you want continue ? [Y/n]" runinstallscript

if [[ $runinstallscript == "Y" ]]||[[ $runinstallscript == "y" ]];then
    echo "start installation"
else
    vim "$buildprof/$3" &&
    source "$buildprof/$3"
fi