#!/bin/bash

function raptor_firms_prep_bluez() {
    if [[ -n $( rfkill | grep bluetooth ) ]];then
        echo "bluez" >> "$raptor_packer"
    fi
}

function raptor_firms_prep_ucode() {
    pack_ucodes=$(grep "vendor_id" /proc/cpuinfo | head -n 1 | awk '{print $3}')

    if [[ "$pack_ucodes" == "GenuineIntel" ]]; then
        echo "intel-ucode" >> "$raptor_packer"
    elif [[ "$pack_ucodes" == "AuthenticAMD" ]]; then
        echo "amd-ucode"   >> "$raptor_packer"
    fi
}

function raptor_firms_prep_iwctl() {

    if [[ -z $( cat $raptor_packer | grep "networkmanager" ) ]]&&[[ -z $( cat $raptor_packer | grep "connman" ) ]];then
        if [[ -n $( rfkill | grep wireless ) ]];then
            echo "iwd" >> "$raptor_packer"
        fi
    fi
}

function raptor_firms_prep_firms() {

    if [[ ! -z $( lspci | grep 'AMD\|Amd') ]];then
        echo "linux-firmware-amdgpu" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'Atheros\|ATHEROS') ]];then
        echo "linux-firmware-atheros" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'Broadcom\|BROADCOM\|Cypress') ]];then
        echo "linux-firmware-broadcom" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'Cirrus\|CIRRUS') ]];then
        echo "linux-firmware-cirrus" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'Intel\|INTEL') ]];then
        echo "linux-firmware-intel" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'MediaTek\|Ralink') ]];then
        echo "linux-firmware-mediatek" >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'NVIDIA\|Nvidia') ]];then
        echo "linux-firmware-nvidia " >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'ATI\|Radeon') ]];then
        echo "linux-firmware-radeon " >> "$raptor_packer"
    fi

    if [[ ! -z $( lspci | grep 'Realtek') ]];then
        echo "linux-firmware-realtek " >> "$raptor_packer"
    fi
}

function raptor_firms_prep_graph_nvid() {
    echo "nvidia";
}

function raptor_firms_prep_graph_rads() {
    echo "nvidia";
}

function raptor_firms_prep_graph_inte() {
    echo "intel";
}

function raptor_firms_prep_graph() {

    if [[ ! -z $( lspci | grep 'VGA' | grep 'Intel Corporation') ]];then
        echo "vulkan-intel" >> "$raptor_packer"
    fi

    if [[ ! -z $(lspci | grep '3d\|NVIDIA') ]];then
        echo "nvidia-utils" >> "$raptor_packer"
        pacstrap /mnt nvidia-utils
    fi

    if [[ ! -z $(lspci | grep '3d\|RADEON') ]];then
        echo "nvidia-radeon" >> "$raptor_packer"
    fi
}

function raptor_firms_prep() {
    raptor_firms_prep_bluez
    raptor_firms_prep_ucode
    raptor_firms_prep_iwctl
    raptor_firms_prep_firms
    raptor_firms_prep_graph
}

## PREP PARTITION
function raptor_disks_init_pure() {
    local ismounted=$( lsblk -o lsblk -o path,mountpoint | grep "/mnt" )
    if [[ ! -z $ismounted ]];then
        umount -R /mnt > /dev/null 2>&1
    fi
}

function raptor_disks_init_swip() {

    if [[ -n $bootpath ]];then
        local pathboot=$( lsblk -o path,label | grep $bootpath )
    fi

    if [[ -n $procpath ]];then
        local pathroot=$( lsblk -o path,label | grep $procpath )
    fi

    if [[ -n $swappath ]];then
        local pathswap=$( lsblk -o path,label | grep $swappath )
    fi

    if [[ -n $homepath ]];then
        local pathhome=$( lsblk -o path,label | grep $homepath )
    fi

    if [[ $dualboot == false ]]&&[[ -z $pathboot ]]&&[[ -z $pathroot ]]&&[[ -z $pathswap ]]&&[[ -z $pathhome ]];then

        read -p "Do yout want swipe partition table : [y/N] " swipe_partition_table

        if [[ $swipe_partition_table == "Y" ]]||[[ $swipe_partition_table == "y" ]];then
            sudo parted -s $loadpath mklabel gpt
        else
            echo "continue installation"
        fi
    fi
}

function raptor_disks_init() {
    raptor_disks_init_pure
    raptor_disks_init_swip
}

## MAKE PARTITION
function raptor_disks_make_boot() {

    local label=$( lsblk -o path,label | grep "BOOT" | awk '{print $1}' )
    local paths=$( lsblk -o path | grep "$bootpath" )
    local sizes=$distro_bootsize

    if [[ -z $label ]]&&[[ -z $paths ]]; then
        echo -e "n\np\n\n\n+$sizes\nt\n\n1\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 1
        bootpath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
        partprobe "$loadpath" && hdparm "$loadpath" > /dev/null 2>&1
    elif [[ -n $paths ]];then
        bootpath=$paths
    elif [[ -n $label ]];then
        bootpath=$label
    else
        echo "error boot partition not found"
        exit 1
    fi

    echo "boot path : $bootpath"
}

function raptor_disks_make_proc() {
    
    local label=$( lsblk -o path,label | grep "ROOT" | awk '{print $1}' )
    local paths=$( lsblk -o path | grep "$procpath" )
    local sizes=$distro_procsize

    if [[ -z $label ]]&&[[ -z $paths ]]; then
        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 1
        procpath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
        partprobe "$loadpath" && hdparm "$loadpath" > /dev/null 2>&1
    elif [[ -n $paths ]];then
        procpath=$paths
    elif [[ -n $label ]];then
        procpath=$label
    else
        echo "error root partition not found"
        exit 1
    fi

    echo "proc path : $procpath"  
}

function raptor_disks_make_swap() {

    local label=$( lsblk -o path,label | grep "swap" | awk '{print $1}' )
    local paths=$( lsblk -o path | grep $swappath )
    local sizes=$distro_swapsize

    if [[ -z $label ]]&&[[ -z $paths ]]; then
        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 1
        swappath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
        partprobe "$loadpath" && hdparm "$loadpath" > /dev/null 2>&1
    elif [[ -n $paths ]];then
        swappath=$paths
    elif [[ -n $label ]];then
        swappath=$label
    else
        echo "error swap partition not found"
        exit 1
    fi

    echo "swap path : $swappath"
}

function raptor_disks_make_home() {

    local label=$( lsblk -o path,label | grep "HOME" | awk '{print $1}' )
    local paths=$( lsblk -o path | grep $homepath )
    local sizes=$distro_homesize

    if [[ -z $label ]]&&[[ -z $paths ]]&&[[ $sizes == "all" ]]; then
        echo -e "n\np\n\n\n\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 1
        homepath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
        partprobe "$loadpath" && hdparm "$loadpath" > /dev/null 2>&1
    elif [[ -z $label ]]&&[[ -z $paths ]]&&[[ $sizes != "all" ]]; then
        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 1
        homepath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
        partprobe "$loadpath" && hdparm "$loadpath" > /dev/null 2>&1
    elif [[ -n $paths ]];then
        homepath=$paths
    elif [[ -n $label ]];then
        homepath=$label
    else
        echo "error home partition not found"
        exit 1
    fi

    echo "home path : $homepath"
}

## dualboot validator team # @Al Muhdil Karim <karim@yuros.org> @Fawaz Rifqi Frasetia <fras@yuros.org>
function raptor_disks_make_uefi() {

    local efipaths=($(lsblk -o path,fstype | grep vfat | awk '{print $1}'))

    for path in "${efipaths[@]}"; do
        sudo mount $path /srv && sleep 2 && 

        if [[ -d "/srv/EFI/Microsoft" ]]; then
            uefipath="$path" && echo "uefi path : $uefipath"
        fi
        sleep 1 && sudo umount -R /srv && sleep 2
    done
}

function raptor_disks_make() {
    clear &&
    echo "STORAGE INFORMATION"
    echo "--------------------------------"
    raptor_disks_make_uefi &&
    raptor_disks_make_boot &&
    raptor_disks_make_proc &&
    raptor_disks_make_swap &&
    raptor_disks_make_home
    echo "--------------------------------"
    read -p 'Type "YES" on capital letter to continue or "NO" to abort installation : ' confirmdiskpartition
    if [[ $confirmdiskpartition != "YES" ]];then
        echo "Proccess cancelation by user"
        exit 1
    fi
}

## FORM PARTITION
function raptor_disks_form_boot() {
    echo "format boot partition"
    mkfs.vfat -F32 -S 4096 -n "BOOT" $bootpath
}

function raptor_disks_form_proc() {
    echo "format root partition"
    mkfs.ext4 -F -q -b 4096 -L "ROOT" $procpath
}

function raptor_disks_form_swap() {
    if [[ -n $swappath ]];then
        echo "format swap partition"
        mkswap $swappath
    fi
}

function raptor_disks_form_home() {
    if [[ $raptor_procmode != "--reset" ]]; then
        echo "format home partition"
        mkfs.ext4 -F -q -b 4096 -L "HOME" $homepath
    fi
}

function raptor_disks_form() {
    clear &&
    echo "FORMATING STORAGE"
    echo "--------------------------------"
    raptor_disks_form_boot &&
    raptor_disks_form_proc &&
    raptor_disks_form_swap &&
    raptor_disks_form_home
}

## MONT PARTITION
function raptor_disks_mont_proc() {
    echo "mount root partition"
    mount $procpath /mnt
    mkdir -p /mnt/{home,boot}
}

function raptor_disks_mont_boot() {
    mount -o uid=0,gid=0,dmask=007,fmask=007 $bootpath /mnt/boot
    mkdir -p /mnt/boot/{efi,kernel,loader}
    mkdir -p /mnt/boot/efi/{boot,linux,systemd}
}

function raptor_disks_mont_uefi() {
    if [[ -n $uefipath ]];then
        mount $uefipath /srv && sleep 1
        sudo cp -r /srv/EFI/Microsoft /mnt/boot/ && sleep 1
        umount -R /srv && sleep 1
    fi
}

function raptor_disks_mont_home() {
    echo "mount home partition"
    mount $homepath /mnt/home
}

function raptor_disks_mont_swap() {
    echo "mount swap partition"
    swapon $swappath
}

function raptor_disks_mont() {
    clear &&
    echo "MOUNTING FILE SYSTEM"
    echo "--------------------------------"
    raptor_disks_mont_proc &&
    raptor_disks_mont_boot &&
    raptor_disks_mont_home &&
    raptor_disks_mont_swap &&
    raptor_disks_mont_uefi 
}

function raptor_disks_prep() {
    clear && echo "Partition configuration"
    raptor_disks_init &&
    raptor_disks_make &&
    raptor_disks_form &&
    raptor_disks_mont &&
    echo "storage configured"
}

function raptor_kerns_prep_pure() {
    rm -f /mnt/etc/mkinitcpio.conf &&
    rm -fr /mnt/etc/mkinitcpio.conf.d 
}

function raptor_kerns_prep() {
    sleep 2 && clear
    echo "Kernel module installation"
    raptor_kerns_prep_pure
}


function raptor_boots_prep() {
    sleep 2 && clear
    echo "Booting module installation"
}

function raptor_neter_prep() {
    sleep 2 && clear
    echo "Network module installation"
}

function raptor_audio_prep() {
    sleep 2 && clear
    echo "Audio module installation"
}

function raptor_deskt_prep() {
    sleep 2 && clear
    echo "Desktop module installation"
}

function raptor_mitig_prep() {
    sleep 2 && clear
    echo "Mitigation module installation"
}

function raptor_secur_prep() {
    sleep 2 && clear
    echo "Security module installation"
}

function raptor_distr_prep() {
    sleep 2 && clear
    echo "Distro module installation"
}

function raptor_cores_prep_mulibs() {

    local ismultilib=$(cat /etc/pacman.conf | grep "[multilib]")

    if [[ -n $distro_libs32 ]]&&[[ $distro_libs32 == true ]];then
        echo "" >>  "/etc/pacman.conf" &&
        echo "[multilib]" >> "/etc/pacman.conf" &&
        echo "Include = /etc/pacman.d/mirrorlist" >> "/etc/pacman.conf"
        echo "enable multilib"
    fi
}

function raptor_cores_prep_pacmir() {
    test -e $raptor_packer && pacstrap /mnt - < $raptor_packer
    if [ $? -ne 0 ]; then
        echo "Error: raptor package installation failed." >&2
        exit 1
    fi
}

function craine_cores_post_config() {
    genfstab -U /mnt > /mnt/etc/fstab &&
    cp -fr $buildconf/* /mnt
    if [ $? -ne 0 ]; then
        echo "Error: raptor configuration installation failed." >&2
        exit 1
    fi
}

function raptor_cores_prep() {
    
    sleep 2 && clear
    echo "Base module installation"
    raptor_cores_prep_mulibs &&
    raptor_cores_prep_pacmir &&
    craine_cores_post_config
}

function raptor_firms_post() {
    echo "firmware post"
}

function craine_cores_post_host() {

    if [[ $hostaname ]];then
        echo "$hostaname" > /mnt/etc/hostname 
    else
        echo "$ID" > /mnt/etc/hostname 
    fi
    locale-gen
}

function craine_cores_post_bash() {
    rm -f /mnt/etc/skel/.bashrc
    rm -f /mnt/etc/skel/.bash_profile
    rm -f /mnt/etc/skel/.bash_logout
}

function raptor_cores_post_time() {
    arch-chroot /mnt ln -sf /usr/share/zoneinfo/$timezone /etc/localtime
    arch-chroot /mnt hwclock --systohc
    arch-chroot /mnt timedatectl set-ntp true
    arch-chroot /mnt timedatectl set-timezone $timezone 
}

function raptor_cores_post_user() {

    echo "create administratif user"
    arch-chroot /mnt useradd -m $username &&

    echo "grant administrator role"
    arch-chroot /mnt usermod -aG wheel $username &&
    
    echo "create user password"
    echo "#!/bin/bash" > /mnt/createuser &&
    echo "echo $username:$password | chpasswd" >> /mnt/createuser &&
    arch-chroot /mnt /bin/bash createuser &&
    rm /mnt/createuser
    sleep 3
}

function raptor_cores_post_srvc() {
    arch-chroot /mnt systemctl enable systemd-timesyncd.service
    arch-chroot /mnt systemctl enable systemd-oomd
}

function raptor_cores_post() {
    sleep 2 && clear
    echo "Base module configuration"
    craine_cores_post_bash
    craine_cores_post_host
    raptor_cores_post_time
    raptor_cores_post_user
    raptor_cores_post_srvc
    echo "Base module configured"
}

function raptor_disks_post() {
    sleep 2 && clear
    echo "Partition configuration"
}

function raptor_kerns_post_conf() {
    
    echo "dualboot : $dualboot"
    if [[ $dualboot == true ]];then
        echo "prepare dual boot kernel preset"
        mv /mnt/etc/mkinitcpio.d/linux-zen-dual.preset /mnt/etc/mkinitcpio.d/linux-zen.preset
        rm /mnt/etc/mkinitcpio.d/linux-zen-mono.preset
    else
        echo "prepare single boot kernel preset"
        mv /mnt/etc/mkinitcpio.d/linux-zen-mono.preset /mnt/etc/mkinitcpio.d/linux-zen.preset
        rm /mnt/etc/mkinitcpio.d/linux-zen-dual.preset
    fi
}


function raptor_kerns_post() {
    sleep 2 && clear
    echo "Kernel module configuration"
    raptor_kerns_post_conf
}

function raptor_neter_post_srvc() {
    arch-chroot /mnt systemctl enable sshd
    arch-chroot /mnt systemctl enable NetworkManager
    arch-chroot /mnt systemctl enable dnsmasq
    arch-chroot /mnt systemctl disable NetworkManager-wait-online.service
}

function raptor_neter_post() {
    sleep 2 && clear
    echo "Network module configuration"
    raptor_neter_post_srvc
}

function raptor_audio_post_srvc() {
    arch-chroot /mnt systemctl enable --global pipewire-pulse.service
}

function raptor_audio_post() {
    sleep 2 && clear
    echo "Audio module configuration"
    raptor_audio_post_srvc 
    echo "Audio module configured"
}



function raptor_deskt_post_serve() {
    arch-chroot /mnt systemctl enable sddm
    arch-chroot /mnt systemctl enable bluetooth.service
}



function raptor_deskt_post() {
    sleep 2 && clear
    echo "Desktop module configuration"
    raptor_deskt_post_serve
    echo "Desktop module configured"
}

function raptor_mitig_post() {
    sleep 2 && clear
    echo "Mitigation module configuration"
}

function raptor_secur_post_serve() {
    arch-chroot /mnt systemctl enable firewalld
}

function raptor_secur_post() {
    sleep 2 && clear
    echo "Security module configuration"
    raptor_secur_post_serve
    echo "Security module configured"
}

function raptor_distr_post() {
    sleep 2 && clear
    echo "Distro module configuration"
}

function raptor_boots_post_prep() {

    if [[ -e /mnt/boot/amd-ucode.img ]]; then
        echo "clean microcode"
        mv /mnt/boot/amd-ucode.img /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/intel-ucode.img ]]; then
        echo "clean microcode"
        mv /mnt/boot/intel-ucode.img /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/vmlinuz-linux ]]; then
        echo "clean vmlinuz"
        kernel_type="vmlinuz-linux"
        mv /mnt/boot/vmlinuz-linux  /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/vmlinuz-linux-zen ]]; then
        echo "clean vmlinuz"
        kernel_type="vmlinuz-linux-zen"
        mv /mnt/boot/vmlinuz-linux-zen  /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/vmlinuz-linux-hardened ]]; then
        echo "clean vmlinuz"
        kernel_type="vmlinuz-linux-hardened"
        mv /mnt/boot/vmlinuz-linux-hardened  /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/vmlinuz-linux-lqx ]]; then
        echo "clean vmlinuz"
        kernel_type="vmlinuz-linux-lqx"
        mv /mnt/boot/vmlinuz-linux-lqx  /mnt/boot/kernel/ 
    fi

    if [[ -e /mnt/boot/vmlinuz-linux-lts ]]; then
        echo "clean vmlinuz"
        kernel_type="vmlinuz-linux-lts"
        mv /mnt/boot/vmlinuz-linux-lts  /mnt/boot/kernel/ 
    fi

    echo "clean initramfs"
    test -e /mnt/boot/initramfs*  && rm -f /mnt/boot/initramfs*

    sleep 1
}

## secure boot @al muhdil karim <karim@yuros.org>, @muhmmad haydar kamil <kamil@yuros.org>, @sultan fajar ramadhan <sultan@yuros.org>
function raptor_boots_post_secu() {

    echo "create secure boot keys"
    arch-chroot /mnt sbctl create-keys &&
   
    if [[ -n $uefipath ]];then
        arch-chroot /mnt sbctl enroll-keys -m -i
        echo "enroll oem boot keys" && sleep 1
    else
        arch-chroot /mnt sbctl enroll-keys -f
        echo "enroll device boot keys" && sleep 1
    fi

    arch-chroot /mnt sbctl sign -s -o /usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed /usr/lib/systemd/boot/efi/systemd-bootx64.efi
    echo "signing systemd-boot efi file" && sleep 2
}

## boot loader @al muhdil karim <karim@yuros.org>, @achmad baihaqi <achmad@yuros.org>, @ibnu dzaky <dzaky@yuros.org>
function raptor_boots_post_boot() {
    echo "setup systemd boot"
    source /mnt/usr/lib/os-release
    echo "root=$rootpath" > /mnt/etc/cmdline.d/01-boot.conf && 
    bootctl --path=/mnt/boot/ --efi-boot-option-description=$ID install
    echo "installation systemd boot"
    sleep 2
}

function raptor_boots_post_srvc() {
    echo "enable boot service"
    arch-chroot /mnt systemctl enable systemd-boot-update.service
    sleep 2
}

function raptor_boots_post() {
    sleep 2 && clear
    echo "Booting module configuration"
    raptor_boots_post_prep &&
    raptor_boots_post_secu &&
    raptor_boots_post_boot && 
    raptor_boots_post_srvc
}

function raptor_prep_install() {
    raptor_firms_prep
    raptor_disks_prep
    raptor_cores_prep
    raptor_kerns_prep
    raptor_boots_prep
    raptor_neter_prep
    raptor_audio_prep
    raptor_deskt_prep
    raptor_mitig_prep
    raptor_secur_prep
    raptor_distr_prep
}

function raptor_post_install() {
    raptor_firms_post
    raptor_cores_post
    raptor_disks_post
    raptor_kerns_post
    raptor_boots_post
    raptor_neter_post
    raptor_audio_post
    raptor_deskt_post
    raptor_mitig_post
    raptor_secur_post
    raptor_distr_post
}

function raptor_post_finishe() {
    echo "finish installation" 
    arch-chroot /mnt mkinitcpio -P &&
    umount -R /mnt
}

function raptor_makes() {
    raptor_prep_install &&
    raptor_post_install &&
    raptor_post_finishe
}